#!/usr/bin/env python3
import numpy as np
import sys
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.spatial.distance import pdist, squareform

def generate_sierpinski_triangle(size, symmetric=True):
    """
    Generate a Sierpinski triangle fractal using bitwise AND method.

    The Sierpinski triangle has a theoretical fractal dimension of log(3)/log(2) ≈ 1.585

    This uses the elegant property that the Sierpinski triangle can be generated by
    checking if (row & col) == col for each position.

    Args:
        size: Size of the square matrix
        symmetric: If True, make the pattern symmetric across the main diagonal

    Returns:
        Binary matrix with Sierpinski triangle pattern
    """
    print(f"Generating Sierpinski triangle of size {size}x{size}...")

    # Initialize empty matrix
    matrix = np.zeros((size, size), dtype=float)

    # Use bitwise method: if (i & j) == j, set to 1
    # This creates the Sierpinski triangle pattern
    if symmetric:
        print("Generating symmetric pattern...")
        for i in range(size):
            for j in range(size):
                # Set both (i,j) and (j,i) to create symmetry
                if (i & j) == j or (j & i) == i:
                    matrix[i, j] = 1
    else:
        for i in range(size):
            for j in range(size):
                if (i & j) == j:
                    matrix[i, j] = 1

    print(f"Generated pattern with {matrix.sum():.0f} filled cells ({matrix.mean()*100:.1f}% density)")

    return matrix

def box_count(matrix, threshold=0.5):
    """
    Calculate fractal dimension using box counting algorithm.

    Args:
        matrix: binary matrix (or continuous matrix to be thresholded)
        threshold: threshold for binarization (default: 0.5)

    Returns:
        fractal_dimension: the estimated fractal dimension
    """
    # Binarize the matrix
    binary_matrix = (matrix > threshold).astype(int)

    # Get matrix dimensions
    n = binary_matrix.shape[0]

    # Box sizes to test (powers of 2 that divide n evenly, plus some others)
    max_box_size = n // 2
    box_sizes = []

    # Generate box sizes: start with powers of 2
    size = 1
    while size <= max_box_size:
        box_sizes.append(size)
        size *= 2

    # Add intermediate sizes for better fitting
    for i in range(len(box_sizes) - 1):
        mid = (box_sizes[i] + box_sizes[i+1]) // 2
        if mid not in box_sizes and mid > box_sizes[i]:
            box_sizes.append(mid)

    box_sizes = sorted(box_sizes)

    print(f"Testing box sizes: {box_sizes}")

    counts = []
    scales = []

    for box_size in box_sizes:
        count = 0
        # Iterate over boxes
        for i in range(0, n, box_size):
            for j in range(0, n, box_size):
                # Extract box
                box = binary_matrix[i:min(i+box_size, n), j:min(j+box_size, n)]
                # Count if box contains any 1s
                if np.any(box):
                    count += 1

        counts.append(count)
        scales.append(1.0 / box_size)
        print(f"Box size {box_size}: {count} boxes")

    # Fit log-log plot
    log_scales = np.log(scales)
    log_counts = np.log(counts)

    # Linear regression
    coeffs = np.polyfit(log_scales, log_counts, 1)
    fractal_dimension = coeffs[0]

    # Calculate R²
    fitted_log_counts = coeffs[0] * log_scales + coeffs[1]
    ss_res = np.sum((log_counts - fitted_log_counts) ** 2)
    ss_tot = np.sum((log_counts - np.mean(log_counts)) ** 2)
    r_squared = 1 - (ss_res / ss_tot)

    print(f"\nFractal dimension: {fractal_dimension:.4f}")
    print(f"R²: {r_squared:.4f}")
    print(f"Theoretical Sierpinski dimension: {np.log(3)/np.log(2):.4f}")

    # Plot the box counting result
    plt.figure(figsize=(10, 6))
    plt.subplot(1, 2, 1)
    plt.loglog(scales, counts, 'bo-', label='Data')
    fit_counts = np.exp(coeffs[1]) * np.array(scales) ** coeffs[0]
    plt.loglog(scales, fit_counts, 'r--', label=f'Fit: D={fractal_dimension:.4f}, R²={r_squared:.4f}')
    plt.xlabel('Scale (1/box size)')
    plt.ylabel('Number of boxes')
    plt.title('Box Counting Method - Synthetic Fractal')
    plt.legend()
    plt.grid(True, alpha=0.3)

    plt.subplot(1, 2, 2)
    plt.imshow(binary_matrix, cmap='binary', interpolation='nearest')
    plt.title('Sierpinski Triangle')

    plt.tight_layout()
    plt.savefig('./output/synthetic/fractal_dimension.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Fractal dimension plot saved as ./output/synthetic/fractal_dimension.png")

    return fractal_dimension, r_squared

def sliding_window_fractal_dimension(matrix, window_size=100, threshold=0.5):
    """
    Calculate fractal dimension using a sliding window across the matrix.

    Args:
        matrix: binary identity matrix
        window_size: size of the sliding window (default: 100)
        threshold: threshold value for plot labeling

    Returns:
        tuple of (positions, fractal_dimensions, r_squared_values) for each window position
    """
    n = matrix.shape[0]

    print(f"\nSliding window analysis:")
    print(f"Matrix size: {n}")
    print(f"Window size: {window_size}")

    if window_size >= n:
        print("Window size >= matrix size, skipping sliding window analysis")
        return [], [], []

    # Pad the matrix with zeros to allow windows at the edges
    pad_size = window_size // 2
    padded_matrix = np.pad(matrix, pad_size, mode='constant', constant_values=0)
    print(f"Padded matrix size: {padded_matrix.shape[0]} (added {pad_size} on each side)")

    fractal_dimensions = []
    r_squared_values = []
    positions = []

    # Slide the window one repeat at a time
    step = 1
    # Now we can slide from 0 to n (inclusive), using the padded matrix
    for start in range(0, n, step):
        end = start + window_size

        # Extract window from padded matrix
        window = padded_matrix[start:end, start:end]

        # Calculate fractal dimension for this window
        # Use simpler box counting without plotting
        binary_matrix = window
        box_sizes = []
        size = 1
        max_box_size = window_size // 2
        while size <= max_box_size:
            box_sizes.append(size)
            size *= 2

        counts = []
        scales = []

        for box_size in box_sizes:
            count = 0
            for i in range(0, window_size, box_size):
                for j in range(0, window_size, box_size):
                    box = binary_matrix[i:min(i+box_size, window_size), j:min(j+box_size, window_size)]
                    if np.any(box):
                        count += 1
            counts.append(count)
            scales.append(1.0 / box_size)

        if len(scales) > 1:
            log_scales = np.log(scales)
            log_counts = np.log(counts)
            coeffs = np.polyfit(log_scales, log_counts, 1)
            fractal_dim = coeffs[0]

            # Calculate R² for this window
            fitted_log_counts = coeffs[0] * log_scales + coeffs[1]
            ss_res = np.sum((log_counts - fitted_log_counts) ** 2)
            ss_tot = np.sum((log_counts - np.mean(log_counts)) ** 2)
            r_squared = 1 - (ss_res / ss_tot)
        else:
            fractal_dim = np.nan
            r_squared = np.nan

        fractal_dimensions.append(fractal_dim)
        r_squared_values.append(r_squared)
        positions.append(start)

        if (start // step) % 100 == 0:
            print(f"Progress: window at position {start}/{n}")

    print(f"Computed {len(fractal_dimensions)} windows")

    # Plot results - basic plots
    plt.figure(figsize=(12, 10))

    plt.subplot(2, 2, 1)
    plt.plot(positions, fractal_dimensions, 'b-', linewidth=1.5)
    plt.xlabel('Position (repeat index)')
    plt.ylabel('Fractal Dimension')
    plt.title(f'Sliding Window Fractal Dimension - Synthetic\n(window={window_size})')
    plt.grid(True, alpha=0.3)
    # Add line for theoretical Sierpinski dimension
    plt.axhline(y=np.log(3)/np.log(2), color='r', linestyle='--',
                label=f'Theoretical D={np.log(3)/np.log(2):.4f}')
    plt.legend()

    plt.subplot(2, 2, 2)
    plt.hist(fractal_dimensions, bins=30, edgecolor='black', alpha=0.7)
    plt.xlabel('Fractal Dimension')
    plt.ylabel('Frequency')
    plt.title('Distribution of Fractal Dimensions')
    plt.axvline(x=np.log(3)/np.log(2), color='r', linestyle='--')
    plt.grid(True, alpha=0.3)

    plt.subplot(2, 2, 3)
    plt.plot(positions, r_squared_values, 'r-', linewidth=1.5)
    plt.xlabel('Position (repeat index)')
    plt.ylabel('R²')
    plt.title('Sliding Window R² Values')
    plt.grid(True, alpha=0.3)

    plt.subplot(2, 2, 4)
    plt.hist(r_squared_values, bins=30, edgecolor='black', alpha=0.7, color='coral')
    plt.xlabel('R²')
    plt.ylabel('Frequency')
    plt.title('Distribution of R² Values')
    plt.grid(True, alpha=0.3)

    plt.tight_layout()
    plt.savefig('./output/synthetic/sliding_window_fractal.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Sliding window plot saved as ./output/synthetic/sliding_window_fractal.png")

    print(f"\nFractal dimension statistics:")
    print(f"  Mean: {np.mean(fractal_dimensions):.4f}")
    print(f"  Std:  {np.std(fractal_dimensions):.4f}")
    print(f"  Min:  {np.min(fractal_dimensions):.4f}")
    print(f"  Max:  {np.max(fractal_dimensions):.4f}")

    print(f"\nR² statistics:")
    print(f"  Mean: {np.mean(r_squared_values):.4f}")
    print(f"  Std:  {np.std(r_squared_values):.4f}")
    print(f"  Min:  {np.min(r_squared_values):.4f}")
    print(f"  Max:  {np.max(r_squared_values):.4f}")

    # Create combined plot with rotated matrix and sliding window
    from scipy.ndimage import rotate

    # Prepare upper triangle and rotate
    masked_matrix = np.copy(matrix).astype(float)
    for i in range(n):
        for j in range(i):
            masked_matrix[i, j] = np.nan

    rotated = rotate(masked_matrix, 45, reshape=True, order=0, cval=np.nan)

    # Create figure with custom layout
    fig = plt.figure(figsize=(14, 8))

    # Top: rotated matrix with adjusted extent to shift down
    ax1 = plt.subplot(2, 1, 1)
    im = plt.imshow(rotated, cmap='binary', interpolation='nearest', aspect='auto')
    # Shift the image down by adjusting the y limits
    ylim = ax1.get_ylim()
    ax1.set_ylim(ylim[0] * 0.5, ylim[1])
    plt.title('Sierpinski Triangle (45° rotation)')
    plt.axis('off')

    # Bottom: sliding window aligned
    ax2 = plt.subplot(2, 1, 2)
    plt.plot(positions, fractal_dimensions, 'b-', linewidth=1.5)
    plt.axhline(y=np.log(3)/np.log(2), color='r', linestyle='--',
                label=f'Theoretical D={np.log(3)/np.log(2):.4f}')
    plt.xlabel('Position (repeat index)')
    plt.ylabel('Fractal Dimension')
    plt.title(f'Sliding Window Fractal Dimension (window={window_size})')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.xlim(0, n)

    plt.tight_layout()
    plt.savefig('./output/synthetic/combined_matrix_fractal.png', dpi=150, bbox_inches='tight')
    plt.close()
    print(f"Combined plot saved as ./output/synthetic/combined_matrix_fractal.png")

    return positions, fractal_dimensions, r_squared_values

def plot_heatmap(matrix, title="Sierpinski Triangle Fractal", filename="synthetic_heatmap.png"):
    """
    Create a heatmap visualization of the fractal matrix.

    Args:
        matrix: numpy array
        title: plot title
        filename: output filename
    """
    plt.figure(figsize=(10, 8))
    sns.heatmap(matrix,
                cmap='RdYlBu_r',
                vmin=0,
                vmax=1,
                square=True,
                cbar_kws={'label': 'Value'},
                rasterized=True)
    plt.title(title)
    plt.xlabel('Index')
    plt.ylabel('Index')
    plt.tight_layout()
    plt.savefig(filename, dpi=150, bbox_inches='tight')
    plt.close()

if __name__ == "__main__":
    import os

    # Usage message
    if len(sys.argv) > 1 and sys.argv[1] in ['-h', '--help', 'help']:
        print("Usage: python synthetic_fractal.py [matrix_size] [window_size]")
        print("\nParameters:")
        print("  matrix_size  - Size of the square matrix (default: 1024)")
        print("                 Use powers of 2 for neat patterns: 256, 512, 1024, 2048, etc.")
        print("  window_size  - Size of sliding window for local analysis (default: 100)")
        print("\nExamples:")
        print("  python synthetic_fractal.py 512 100    # 512x512 matrix, window=100")
        print("  python synthetic_fractal.py 1024       # 1024x1024 matrix, default window")
        print("  python synthetic_fractal.py            # All defaults (1024x1024, window=100)")
        sys.exit(0)

    # Create output directory
    os.makedirs('./output/synthetic', exist_ok=True)

    # Configuration
    if len(sys.argv) > 1:
        matrix_size = int(sys.argv[1])
    else:
        matrix_size = 1024  # Default size

    if len(sys.argv) > 2:
        window_size = int(sys.argv[2])
    else:
        window_size = 100  # Default window size

    print(f"=== Generating Synthetic Sierpinski Triangle Fractal ===")
    print(f"Matrix size: {matrix_size}")
    print(f"Window size: {window_size}")
    print(f"Theoretical fractal dimension: {np.log(3)/np.log(2):.4f}")

    # Check if size is power of 2
    is_power_of_2 = (matrix_size & (matrix_size - 1)) == 0 and matrix_size != 0
    if not is_power_of_2:
        nearest_lower = 2 ** int(np.log2(matrix_size))
        nearest_higher = 2 ** (int(np.log2(matrix_size)) + 1)
        print(f"\n⚠️  WARNING: {matrix_size} is not a power of 2!")
        print(f"   Sierpinski triangles fit neatly into power-of-2 sizes.")
        print(f"   Suggested sizes: {nearest_lower} or {nearest_higher}")
        print(f"   Common sizes: 256, 512, 1024, 2048, 4096")
        print(f"   The pattern will be cut off at the edges.\n")
    else:
        print(f"✓ Size {matrix_size} is a power of 2 - pattern will fit neatly!\n")

    # Generate Sierpinski triangle (already symmetric)
    symmetric_fractal = generate_sierpinski_triangle(matrix_size, symmetric=True)

    print(f"\nFractal matrix statistics:")
    print(f"  Shape: {symmetric_fractal.shape}")
    print(f"  Fraction of 1s: {symmetric_fractal.mean():.4f}")
    print(f"  Min: {symmetric_fractal.min():.4f}")
    print(f"  Max: {symmetric_fractal.max():.4f}")

    # Save heatmap
    print("\nSaving heatmap...")
    plot_heatmap(symmetric_fractal,
                title=f"Sierpinski Triangle Fractal ({matrix_size}x{matrix_size})",
                filename="./output/synthetic/heatmap.png")
    print("Heatmap saved as ./output/synthetic/heatmap.png")

    print("\n=== Computing fractal dimension ===")
    d, r2 = box_count(symmetric_fractal, threshold=0.5)

    print("\n=== Computing sliding window fractal dimension ===")
    positions, dims, r2_vals = sliding_window_fractal_dimension(
        symmetric_fractal,
        window_size=window_size,
        threshold=0.5
    )

    print("\n=== Summary ===")
    print(f"Overall fractal dimension: {d:.4f} (R² = {r2:.4f})")
    print(f"Theoretical Sierpinski dimension: {np.log(3)/np.log(2):.4f}")
    print(f"Difference from theoretical: {abs(d - np.log(3)/np.log(2)):.4f}")
