#!/usr/bin/env python3
"""
Generate reference data for regression testing.
Run this when you're confident the simulation is working correctly
to create "golden" reference files for future testing.
"""

import sys
import random
import numpy as np
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from censim.simulation import read_sequence, introduce_mutations


def generate_reference_files():
    """Generate reference files for regression testing."""

    ref_dir = Path("./test_reference_data")
    ref_dir.mkdir(exist_ok=True)

    # Reference test cases: (seed, generations, description)
    test_cases = [
        (42, 50, "small_test"),
        (123, 100, "medium_test"),
        (999, 200, "large_test"),
    ]

    print("Generating reference data for regression testing...")
    print("=" * 60)

    # Read input files once
    sequence = read_sequence("./data/15000copy_cen178.seq")

    for seed, generations, description in test_cases:
        print(f"\nGenerating {description}: seed={seed}, generations={generations}")

        # Output files
        fasta_ref = ref_dir / f"{description}_seed{seed}_{generations}gen.fa"
        record_ref = ref_dir / f"{description}_seed{seed}_{generations}gen.record.txt"
        cenh3_ref = ref_dir / f"{description}_seed{seed}_{generations}gen.cenh3.txt"

        try:
            # Set random seeds
            random.seed(seed)
            np.random.seed(seed)

            # Run simulation
            mutated_sequence, mutation_records, cenh3_occupancy, collapsed = introduce_mutations(
                sequence, 0, generations
            )

            # Write output files (no FASTA header to match old CLI behavior)
            with open(fasta_ref, "w") as f:
                f.write(mutated_sequence + '\n')

            with open(record_ref, "w") as f:
                for record in mutation_records:
                    gen, mut_type, idx, ref, mut, copy_num = record
                    f.write(f"{gen}, {mut_type}, {idx}, {ref}, {mut}, {copy_num}\n")

            with open(cenh3_ref, "w") as f:
                for idx, occupied in enumerate(cenh3_occupancy):
                    if occupied:
                        f.write(f"{idx}\t1\n")
                    else:
                        f.write(f"{idx}\t0\n")

            print(f"✅ Generated {description}")
            print(f"   FASTA: {fasta_ref.name}")
            print(f"   Records: {record_ref.name}")

        except Exception as e:
            print(f"❌ Failed to generate {description}: {e}")
            continue

    # Create metadata file
    metadata_file = ref_dir / "reference_metadata.txt"
    with open(metadata_file, 'w') as f:
        f.write("# Reference data metadata\n")
        f.write("# Generated by generate_reference_data.py\n")
        f.write("# Do not modify these files manually\n")
        f.write("#\n")
        f.write("# Test cases:\n")
        for seed, generations, description in test_cases:
            f.write(f"# {description}: seed={seed}, generations={generations}\n")

    print(f"\n{'='*60}")
    print("✅ Reference data generation complete!")
    print(f"📁 Files saved to: {ref_dir}")
    print("\nTo use for regression testing:")
    print("  python -m pytest test_reproducibility.py::test_regression_against_reference -v")


if __name__ == "__main__":
    generate_reference_files()