#!/usr/bin/env python3
"""
Generate reference data for regression testing.
Run this when you're confident the simulation is working correctly
to create "golden" reference files for future testing.
"""

import subprocess
import shutil
from pathlib import Path


def generate_reference_files():
    """Generate reference files for regression testing."""

    ref_dir = Path("./test_reference_data")
    ref_dir.mkdir(exist_ok=True)

    # Reference test cases: (seed, generations, description)
    test_cases = [
        (42, 50, "small_test"),
        (123, 100, "medium_test"),
        (999, 200, "large_test"),
    ]

    print("Generating reference data for regression testing...")
    print("=" * 60)

    for seed, generations, description in test_cases:
        print(f"\nGenerating {description}: seed={seed}, generations={generations}")

        # Output files
        fasta_ref = ref_dir / f"{description}_seed{seed}_{generations}gen.fa"
        record_ref = ref_dir / f"{description}_seed{seed}_{generations}gen.record.txt"
        pos_ref = ref_dir / f"{description}_seed{seed}_{generations}gen.pos"

        # Run simulation
        cmd = [
            "python", "-m", "censim.simulation",
            "./data/15000copy_cen178.seq", str(generations),
            "./data/15000copy_cen178.178bp.bed.pos",
            str(fasta_ref), str(record_ref), str(pos_ref),
            "--seed", str(seed)
        ]

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
            if result.returncode != 0:
                print(f"❌ Failed to generate {description}: {result.stderr}")
                continue

            print(f"✅ Generated {description}")
            print(f"   FASTA: {fasta_ref.name}")
            print(f"   Records: {record_ref.name}")
            print(f"   Positions: {pos_ref.name}")

        except subprocess.TimeoutExpired:
            print(f"❌ {description} timed out")
            continue

    # Create metadata file
    metadata_file = ref_dir / "reference_metadata.txt"
    with open(metadata_file, 'w') as f:
        f.write("# Reference data metadata\n")
        f.write("# Generated by generate_reference_data.py\n")
        f.write("# Do not modify these files manually\n")
        f.write("#\n")
        f.write("# Test cases:\n")
        for seed, generations, description in test_cases:
            f.write(f"# {description}: seed={seed}, generations={generations}\n")

    print(f"\n{'='*60}")
    print("✅ Reference data generation complete!")
    print(f"📁 Files saved to: {ref_dir}")
    print("\nTo use for regression testing:")
    print("  python -m pytest test_reproducibility.py::test_regression_against_reference -v")


if __name__ == "__main__":
    generate_reference_files()